# Generated by Django 3.0.4 on 2020-03-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
