# Generated by Django 3.0.4 on 2020-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0003_auto_20200328_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='thumbText',
            field=models.TextField(blank=True),
        ),
    ]
