# Generated by Django 3.0.4 on 2020-03-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0004_printjob_thumbtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='thumbText',
        ),
    ]
