# Generated by Django 3.0.4 on 2020-03-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0005_remove_printjob_thumbtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='testText',
            field=models.TextField(blank=True),
        ),
    ]
