# Generated by Django 3.0.4 on 2020-03-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0006_printjob_testtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='testText',
        ),
    ]
