# Generated by Django 3.0.4 on 2020-03-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintProcess', '0007_remove_printjob_testtext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintJob',
            new_name='PrintJobData',
        ),
    ]
